### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by gerrywastaken** [florian/rb_heap#1]
I just wanted to thank you for releasing this despite its limited use by the community. I ended up writing my own after noticing awful performance with other implementations out there.

I was noticing huge performance improvements over all the other implementations until I got to yours, which isn't surprising as you seem to be doing mostly the same but with much prettier code. I hope some day this repo gets the attention it deserves, but either way... thank you.

**Comment by florian** [comment]
Aww, thank you so much for the nice words! I'm super happy to hear that. :)
