### ISSUE TITLE
Incorrect .to_a implementation

### ISSUE THREAD

**Issue by ro31337** [florian/rb_heap#2]
Steps to reproduce:

```ruby
heap = Heap.new(:<)
heap << 2 << 1 << 3 << 4 << 6 << 5
heap.pop
puts heap.to_a.inspect
```

Result:

```
[2, 4, 3, 5, 6, nil]
```

Expected (without `nil`):

```
[2, 4, 3, 5, 6]
```

Description: `heap.pop` mixes up things a little bit. Works without `pop` as expected (there is even existing test for that)

**Comment by florian** [comment]
Nice catch. The space from the pushs stays allocated, which generally seems reasonable, but messes up the `to_a` here.
I've pushed https://github.com/florian/rb_heap/commit/3d91e17997f0b2f48a27a73e9023b684c140e3a7 to fix it.

btw, I'm curious how this got so much attention (15 thumbs up): Were you using rb_heap for anything specific? :)
The repo has 9 stars, so I didn't expect that many reactions.

**Comment by ro31337** [comment]
Thanks!

There is a Russian Telegram group of folks who learn Ruby, some of these discussions is the explanation of the surge of thumbs up :) Personally, I use it for leetcode questions, some other folks I suspect do it as well, since there is no heap data structure in Ruby

**Comment by florian** [comment]
Oh, that's really cool to hear!
I definitely needed that a few times for leetcode, too.
